;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ergoemacs-ctl-c
        eval-last-sexp
        mouse-set-region
        org-backward-sentence
        read-only-mode
        set-rectangular-region-anchor
        tabbar-switch-to-default-grouping
        yank-rectangle
        ))

(setq mc/cmds-to-run-once
      '(
        compose-mail
        lawlist-popup-context-menu
        org-self-insert-command
        ))
