;; Install extensions if they're missing
(defvar distopico-packages
   '(s
     cl
     dash
     cl-lib
     es-lib
     magit
     iedit
     paredit
     icicles
     diminish
     move-text
     column-marker
     web-beautify
     god-mode
     gist
     tabbar
     htmlize
     highlight-symbol
     visual-regexp
     flycheck
     flycheck-color-mode-line
     flx
     flx-ido
     jump-char
     smex
     jedi
     direx
     dired+
     dired-details+
     helm
     helm-projectile
     css-eldoc
     less-css-mode
     markdown-mode
     skewer-less
     perspective
     smartparens
     projectile
     es-windows
     ido-ubiquitous
     ido-vertical-mode
     ido-at-point
     simple-httpd
     smart-forward
     move-dup
     nodejs-repl
     restclient
     rainbow-identifiers
     rainbow-delimiters
     ido-ubiquitous
     mouse-slider-mode
     highlight-escape-sequences
     whitespace-cleanup-mode
     elisp-slime-nav
     git-commit-mode
     gitconfig-mode
     gitignore-mode
     dropdown-list
     window-numbering
     smart-tabs-mode
     fill-column-indicator
     browse-kill-ring
     highlight-indentation
     find-file-in-project
     php-extras
     php-auto-yasnippets
     pony-mode
     ac-python
     ac-emmet
     ac-js2
     js3-mode
     js2-mode
     js2-refactor
     json-mode
     iy-go-to-char
     tabkey2
     fic-mode
     )
       "A list of packages to ensure are installed at launch."
)

(provide 'my-package)
